import { useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts'
import { Activity, CreditCard, DollarSign, TrendingUp, Users, Wifi } from 'lucide-react'
import { format } from 'date-fns'
import api from '@/lib/api'
import { formatCurrency, formatNumber } from '@/lib/formatters'

const chartColors = ['#23C7D9', '#4F8CFF', '#FFB020', '#F75FB2']

function MetricCard({ label, value, note, icon: Icon, title }) {
  return (
    <div className="rounded-3xl border border-gray-100 bg-white p-5 shadow-sm" title={title}>
      <div className="flex items-center justify-between gap-3">
        <p className="text-xs font-medium uppercase tracking-[0.22em] text-gray-500">{label}</p>
        <div className="rounded-2xl bg-primary-50 p-2 text-primary-600">
          <Icon size={16} />
        </div>
      </div>
      <p className="mt-4 text-3xl font-bold text-gray-900">{value}</p>
      <p className="mt-2 text-sm text-gray-900">{note}</p>
    </div>
  )
}

function EmptyChartState({ text }) {
  return (
    <div className="flex h-[260px] items-center justify-center rounded-3xl border border-dashed border-gray-200 bg-gray-50 text-sm text-gray-500">
      {text}
    </div>
  )
}

export default function AdminDashboard() {
  const { data: dash, isLoading } = useQuery({
    queryKey: ['admin-dashboard'],
    queryFn: () => api.get('/admin/dashboard').then((response) => response.data),
    refetchInterval: 30000,
  })

  const { data: analytics } = useQuery({
    queryKey: ['admin-analytics', 30],
    queryFn: () => api.get('/analytics/platform?days=30').then((response) => response.data),
  })

  const sourceData = useMemo(
    () => analytics?.sourceBreakdown || dash?.revenue30dBreakdown || [],
    [analytics?.sourceBreakdown, dash?.revenue30dBreakdown]
  )

  const topTenants = analytics?.topTenants || []
  const timeline = dash?.revenueTrend || analytics?.timeline || []
  const rollingRevenue = dash?.revenue30d || analytics?.totalRevenue || 0
  const averageRevenuePerTenant = dash?.tenants?.active
    ? rollingRevenue / dash.tenants.active
    : 0
  const strongestSource = sourceData.slice().sort((a, b) => b.value - a.value)[0]

  if (isLoading) {
    return (
      <div className="p-8">
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {[1, 2, 3, 4, 5, 6].map((item) => (
            <div key={item} className="h-36 animate-pulse rounded-3xl bg-gray-100" />
          ))}
        </div>
      </div>
    )
  }

  return (
    <div className="p-8">
      <div className="rounded-[36px] border border-gray-100 bg-white p-6 shadow-sm">
        <div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between">
          <div>
            <p className="text-xs font-medium uppercase tracking-[0.22em] text-primary-600">Platform overview</p>
            <h1 className="mt-3 text-4xl font-bold text-gray-900">Platform analytics</h1>
            <p className="mt-3 max-w-2xl text-sm leading-relaxed text-gray-900">
              Track combined revenue, tenant momentum, live activity, and how earnings split across subscriptions, shop sales, and services.
            </p>
          </div>
          <div className="rounded-3xl border border-gray-100 bg-gray-50 px-5 py-4 text-right">
            <p className="text-xs uppercase tracking-[0.2em] text-gray-500">Today</p>
            <p className="mt-2 text-lg font-semibold text-gray-900">{format(new Date(), 'EEEE, MMMM d yyyy')}</p>
          </div>
        </div>

        <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <MetricCard
            label="Gross Tenant Revenue"
            value={formatCurrency(analytics?.totalTenantRevenue || 0)}
            note="Tenant earnings generated across all hotspots."
            title="Total value generated by tenants using FlowFi"
            icon={TrendingUp}
          />
          <MetricCard
            label="Revenue (30d)"
            value={formatCurrency(rollingRevenue)}
            note="Subscriptions, shop sales, and confirmed services combined."
            icon={DollarSign}
          />
          <MetricCard
            label="Today's revenue"
            value={formatCurrency(dash?.todayRevenue || 0)}
            note="All paid revenue sources collected today."
            icon={CreditCard}
          />
          <MetricCard
            label="Active tenants"
            value={formatNumber(dash?.tenants?.active || 0)}
            note={`${formatNumber(dash?.tenants?.pending || 0)} pending review.`}
            icon={Users}
          />
          <MetricCard
            label="New tenants (30d)"
            value={formatNumber(analytics?.newTenants || 0)}
            note="Fresh workspaces added during the current 30-day window."
            icon={TrendingUp}
          />
          <MetricCard
            label="Sessions (30d)"
            value={formatNumber(analytics?.totalSessions || 0)}
            note={`${formatNumber(dash?.activeSessions || 0)} sessions are active right now.`}
            icon={Activity}
          />
          <MetricCard
            label="Avg per active tenant"
            value={formatCurrency(averageRevenuePerTenant)}
            note="Based on total combined platform revenue in the last 30 days."
            icon={Wifi}
          />
        </div>

        <div className="mt-8 rounded-[30px] border border-gray-100 bg-gray-50 p-5">
          <div className="mb-5">
            <p className="text-sm font-semibold text-gray-900">Revenue breakdown</p>
            <p className="mt-1 text-sm text-gray-900">See the 30-day split across subscriptions, shop sales, and services at a glance.</p>
          </div>
          <div className="grid gap-4 md:grid-cols-3">
            {sourceData.map((entry) => {
              const share = rollingRevenue ? ((Number(entry.value || 0) / Number(rollingRevenue)) * 100).toFixed(1) : '0.0'

              return (
                <div key={entry.key || entry.label} className="rounded-3xl bg-white p-5">
                  <p className="text-xs uppercase tracking-[0.2em] text-gray-500">{entry.label}</p>
                  <p className="mt-3 text-2xl font-bold text-gray-900">{formatCurrency(entry.value)}</p>
                  <p className="mt-2 text-sm text-gray-600">{share}% of 30-day platform revenue</p>
                </div>
              )
            })}
          </div>
        </div>

        <div className="mt-8 grid gap-6 xl:grid-cols-[1.35fr,0.65fr]">
          <div className="rounded-[30px] border border-gray-100 bg-gray-50 p-5">
            <div className="mb-5 flex items-center justify-between gap-4">
              <div>
                <p className="text-sm font-semibold text-gray-900">Revenue trend</p>
                <p className="mt-1 text-sm text-gray-900">Combined revenue across subscriptions, shop sales, and services in the last 30 days.</p>
              </div>
              <div className="grid gap-2 text-right sm:grid-cols-2 sm:text-left">
                <div className="rounded-2xl bg-white px-4 py-3">
                  <p className="text-[11px] uppercase tracking-[0.2em] text-gray-500">Live sessions</p>
                  <p className="mt-2 text-lg font-semibold text-gray-900">{formatNumber(dash?.activeSessions || 0)}</p>
                </div>
                <div className="rounded-2xl bg-white px-4 py-3">
                  <p className="text-[11px] uppercase tracking-[0.2em] text-gray-500">Total tenants</p>
                  <p className="mt-2 text-lg font-semibold text-gray-900">{formatNumber(dash?.tenants?.total || 0)}</p>
                </div>
              </div>
            </div>

            {timeline.length > 0 ? (
              <ResponsiveContainer width="100%" height={280}>
                <AreaChart data={timeline}>
                  <defs>
                    <linearGradient id="adminRevenueFill" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#23C7D9" stopOpacity={0.45} />
                      <stop offset="95%" stopColor="#23C7D9" stopOpacity={0.03} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid vertical={false} stroke="#e5e7eb" />
                  <XAxis dataKey="date" tickFormatter={(value) => value.slice(5)} tick={{ fill: '#6b7280', fontSize: 11 }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fill: '#6b7280', fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={(value) => `KES ${Math.round(value / 1000)}k`} />
                  <Tooltip
                    formatter={(value) => [formatCurrency(value), 'Revenue']}
                    labelFormatter={(value) => `Date: ${value}`}
                    contentStyle={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: '18px', color: '#111827' }}
                  />
                  <Area type="monotone" dataKey="revenue" stroke="#23C7D9" strokeWidth={3} fill="url(#adminRevenueFill)" />
                </AreaChart>
              </ResponsiveContainer>
            ) : (
              <EmptyChartState text="Revenue starts plotting here once transactions begin." />
            )}
          </div>

          <div className="space-y-6">
            <div className="rounded-[30px] border border-gray-100 bg-gray-50 p-5">
              <p className="text-sm font-semibold text-gray-900">Revenue source mix</p>
              <p className="mt-1 text-sm text-gray-900">How the current 30-day revenue total is split by source.</p>
              {sourceData.length > 0 ? (
                <>
                  <div className="mt-4 h-[200px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie data={sourceData} dataKey="value" innerRadius={55} outerRadius={80} paddingAngle={4}>
                          {sourceData.map((entry, index) => (
                            <Cell key={entry.key || entry.label} fill={chartColors[index % chartColors.length]} />
                          ))}
                        </Pie>
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                  <div className="space-y-3">
                    {sourceData.map((entry, index) => (
                      <div key={entry.key || entry.label} className="flex items-center justify-between gap-3 rounded-2xl bg-white px-4 py-3">
                        <div className="flex items-center gap-3">
                          <span className="h-3 w-3 rounded-full" style={{ backgroundColor: chartColors[index % chartColors.length] }} />
                          <span className="text-sm text-gray-900">{entry.label}</span>
                        </div>
                        <span className="text-sm font-semibold text-gray-900">{formatCurrency(entry.value)}</span>
                      </div>
                    ))}
                  </div>
                </>
              ) : (
                <EmptyChartState text="Revenue sources will appear here once payments begin landing." />
              )}
            </div>

            <div className="rounded-[30px] border border-gray-100 bg-gray-50 p-5">
              <p className="text-sm font-semibold text-gray-900">Platform snapshot</p>
              <div className="mt-4 space-y-3">
                {[
                  { label: 'Pending tenants', value: formatNumber(dash?.tenants?.pending || 0) },
                  { label: 'Largest revenue source', value: strongestSource ? strongestSource.label : 'No data yet' },
                ].map((item) => (
                  <div key={item.label} className="rounded-2xl bg-white px-4 py-3">
                    <p className="text-[11px] uppercase tracking-[0.2em] text-gray-500">{item.label}</p>
                    <p className="mt-2 text-lg font-semibold text-gray-900">{item.value}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8 rounded-[30px] border border-gray-100 bg-gray-50 p-5">
          <div className="mb-5 flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-gray-900">Global Hotspot Activity</p>
              <p className="mt-1 text-sm text-gray-900">Total value generated by tenants across the platform.</p>
            </div>
          </div>

          {timeline.length > 0 ? (
            <ResponsiveContainer width="100%" height={280}>
              <AreaChart data={timeline}>
                <defs>
                  <linearGradient id="tenantEarningsFill" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.45} />
                    <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0.03} />
                  </linearGradient>
                </defs>
                <CartesianGrid vertical={false} stroke="#e5e7eb" />
                <XAxis dataKey="date" tickFormatter={(value) => value.slice(5)} tick={{ fill: '#6b7280', fontSize: 11 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: '#6b7280', fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={(value) => `KES ${Math.round(value / 1000)}k`} />
                <Tooltip
                  formatter={(value) => [formatCurrency(value), 'Tenant Earnings']}
                  labelFormatter={(value) => `Date: ${value}`}
                  contentStyle={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: '18px', color: '#111827' }}
                />
                <Area type="monotone" dataKey="tenantRevenue" stroke="#8b5cf6" strokeWidth={3} fill="url(#tenantEarningsFill)" />
              </AreaChart>
            </ResponsiveContainer>
          ) : (
            <EmptyChartState text="Tenant earnings will appear here once hotspots start making money." />
          )}
        </div>
      </div>

      <div className="mt-8 grid gap-6 xl:grid-cols-[1.1fr,0.9fr]">
        <div className="rounded-[32px] border border-gray-100 bg-white p-6 shadow-sm">
          <div className="mb-5">
            <p className="text-sm font-semibold text-gray-900">Top performing tenants</p>
            <p className="mt-1 text-sm text-gray-900">Ranked by tenant-linked revenue contribution in the current 30-day window.</p>
          </div>

          {topTenants.length > 0 ? (
            <div className="grid gap-6 lg:grid-cols-[1.1fr,0.9fr]">
              <div className="h-[260px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={topTenants.slice(0, 5)} layout="vertical" margin={{ left: 16 }}>
                    <CartesianGrid horizontal={false} stroke="#e5e7eb" />
                    <XAxis type="number" tick={{ fill: '#6b7280', fontSize: 11 }} axisLine={false} tickLine={false} />
                    <YAxis type="category" dataKey="name" width={110} tick={{ fill: '#111827', fontSize: 11 }} axisLine={false} tickLine={false} />
                    <Tooltip
                      formatter={(value) => [formatCurrency(value), 'Revenue']}
                      contentStyle={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: '18px', color: '#111827' }}
                    />
                    <Bar dataKey="revenue" radius={[0, 10, 10, 0]} fill="#4F8CFF" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
              <div className="space-y-3">
                {topTenants.slice(0, 5).map((tenant, index) => (
                  <div key={tenant.name} className="rounded-3xl border border-gray-100 bg-gray-50 p-4">
                    <div className="flex items-center justify-between gap-3">
                      <div className="flex items-center gap-3">
                        <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary-50 text-sm font-semibold text-primary-700">
                          {String(index + 1).padStart(2, '0')}
                        </div>
                        <div>
                          <p className="text-sm font-semibold text-gray-900">{tenant.name}</p>
                          <p className="text-xs text-gray-500">Revenue contribution</p>
                        </div>
                      </div>
                      <p className="text-sm font-semibold text-gray-900">{formatCurrency(tenant.revenue)}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <EmptyChartState text="Tenant ranking appears here once payment activity is recorded." />
          )}
        </div>

        <div className="rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-gray-100">
          <p className="text-sm font-semibold text-gray-900">What to watch next</p>
          <div className="mt-5 space-y-4">
            {[
              {
                label: 'Tenant approvals',
                value: formatNumber(dash?.tenants?.pending || 0),
                note: 'Pending workspaces waiting for platform review.',
              },
              {
                label: 'Live activity',
                value: formatNumber(dash?.activeSessions || 0),
                note: 'Sessions active right now across all tenants.',
              },
              {
                label: 'Revenue breadth',
                value: topTenants.length > 1 ? `${formatNumber(topTenants.length)} active contributors` : 'Limited data',
                note: 'Use this to judge whether growth is broad or concentrated in a few venues.',
              },
            ].map((item) => (
              <div key={item.label} className="rounded-3xl bg-gray-50 p-5">
                <p className="text-xs font-medium uppercase tracking-[0.2em] text-gray-500">{item.label}</p>
                <p className="mt-2 text-2xl font-bold text-gray-900">{item.value}</p>
                <p className="mt-2 text-sm text-gray-700">{item.note}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
